/*
 * sample job worker api for the 'fireworq'
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostResponse struct {

	Status string `json:"status,omitempty"`

	Message string `json:"message,omitempty"`
}
